# Generated by Django 5.2 on 2025-06-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('cliente', models.CharField(max_length=50)),
                ('tipo_servico', models.CharField(max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_proposta', models.CharField(max_length=20)),
            ],
        ),
    ]
