# Generated by Django 5.2 on 2025-06-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='data_emissao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero_proposta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status_proposta',
            field=models.CharField(choices=[('aprovada', 'APROVADA'), ('pendente', 'PENDENTE'), ('rejeitada', 'REJEITADA')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tipo_servico',
            field=models.CharField(choices=[('transporte', 'TRANSPORTE'), ('armazem', 'ARMAZÉM')], default='transporte', max_length=10),
        ),
    ]
