# Generated by Django 5.2 on 2025-06-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0002_alter_proposta_data_emissao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
        migrations.AlterField(
            model_name='proposta',
            name='cliente',
            field=models.CharField(max_length=50, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero_proposta',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número da Proposta'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status_proposta',
            field=models.CharField(choices=[('aprovada', 'APROVADA'), ('pendente', 'PENDENTE'), ('rejeitada', 'REJEITADA')], default='pendente', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tipo_servico',
            field=models.CharField(choices=[('transporte', 'TRANSPORTE'), ('armazem', 'ARMAZÉM')], default='transporte', max_length=10, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
    ]
