# Generated by Django 5.2 on 2025-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_comercial', '0003_alter_proposta_options_alter_proposta_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='numero_proposta',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número da Proposta'),
        ),
    ]
